# The structure of retrieval and multi_agents can be modified in this yaml file
# agent and model configurations should be modified in their respective config folders

defaults:
  - retrieval: text # Change this to text/image when configuring retrieval
  - _self_

run-name: mmlb-MDA # Experiment name

dataset:
  top_k: 4 # Top-k results used during inference

retrieval:
  top_k: 10 # Top-k results returned during retrieval
  cuda_visible_devices: '0'

mdoc_agent:
  cuda_visible_devices: '0,1,2,3'
  truncate_len: null # Used for debugging; set to null for normal use
  save_freq: 10 # Frequency of saving checkpoints
  ans_key: ans_${run-name} # Key name for generated answers during prediction
  save_message: true # Set to true to record responses from all agents

  agents:
    - agent: image_agent # Configures prompt and controls whether to use text/image as reference material
      model: qwen2vl # Configures the model to use
    - agent: text_agent
      model: llama31
    - agent: general_agent
      model: qwen2vl
  
  sum_agent:
    agent: sum_agent # Responsible for summarizing answers from all agents
    model: qwen2vl

react_agent:
  cuda_visible_devices: ${mdoc_agent.cuda_visible_devices}
  truncate_len: ${mdoc_agent.truncate_len}
  save_freq: ${mdoc_agent.save_freq}
  ans_key: ans_${run-name}_react # Key name for generated answers during prediction
  save_message: ${mdoc_agent.save_message}
  max_iterations: 5  # Maximum number of ReAct iterations
  top_k: 4  # Top-k results used during each ReAct iteration
  
  agents:
    - agent: general_agent # Main agent for ReAct process
      model: qwen2vl # Configures the model to use

  retrieval:
    image_retriever:
      model_type: image
      model_name: ColpaliRetrieval
      embed_dir: ./tmp/${retrieval.model_name}/${retrieval.image_question_key}
      batch_size: 2
      top_k: ${retrieval.top_k}
      doc_key: doc_id
      image_question_key: question
      r_image_key: r_image
      r_image_index_key: r_image_index

    text_retriever:
      model_type: text
      model_name: ColbertRetrieval
      top_k: ${retrieval.top_k}
      doc_key: doc_id
      text_question_key: question
      r_text_key: r_text
      r_text_index_key: r_text_index

reflection_agent:
  cuda_visible_devices: ${mdoc_agent.cuda_visible_devices}
  truncate_len: ${mdoc_agent.truncate_len}
  save_freq: ${mdoc_agent.save_freq}
  ans_key: ${mdoc_agent.ans_key}
  save_message: ${mdoc_agent.save_message}
  max_reflection_iter: 3  # Maximum number of reflection iterations
  confidence_threshold: 0.8  # Confidence threshold to stop reflection
  
  agents:
    - agent: general_agent # Configures prompt and controls whether to use text/image as reference material
      model: qwen2vl # Configures the model to use

eval_agent: # Used for result evaluation
  truncate_len: null # Used for debugging; set to null for normal use
  ans_key: ans_${run-name}
  agent: base
  model: openai
